@host = http://localhost:3000/api/v1

###
GET {{host}}

###
GET {{host}}/products?size=6

###
GET {{host}}/nueva-ruta

### parametros
GET {{host}}/categories/123/products/sadfokms3

### Parametros query
GET {{host}}/users?limit=10&offset=200
